<a href="https://colab.research.google.com/github/M339KUMAR/ColabDemoFiles/blob/main/GCAF/geocoding_using_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
web_link = 'https://en.wikipedia.org/wiki/List_of_most-visited_museums'

museums = pd.read_html(web_link)

In [ ]:
museums

[                                                !Name  \
 0                                              Louvre
 1                                     Vatican Museums
 2                            National Museum of China
 3                                      British Museum
 4                              Natural History Museum
 ..                                                ...
 69                      Palacio de Cristal del Retiro
 70  Museum of European and Mediterranean Civilisat...
 71                          Scottish National Gallery
 72                         National Gallery Singapore
 73                                  Museo Reina Sof√≠a

    Visitors in 2023 or 2022          City         Country
 0       8,900,000 (2023)[1]         Paris          France
 1       6,800,000 (2023)[2]  Vatican City         Vatican
 2       6,765,000 (2023)[3]       Beijing           China
 3       5,820,860 (2023)[4]        London  United Kingdom
 4       5,688,608 (2023)[5]        London  United Kingdom
 ..                      ...           ...             ...
 69         1,318,823[b][38]        Madrid           Spain
 70         1,300,000 (2023)     Marseille          France
 71            1,277,230[38]     Edinburgh  United Kingdom
 72                      NaN     Singapore       Singapore
 73         1,253,183[c][38]        Madrid           Spain

 [74 rows x 4 columns]]

In [ ]:
type(museums)

list

In [ ]:
len(museums)

1

In [ ]:
type(museums[0])

pandas.core.frame.DataFrame

In [ ]:
museums = museums[0]
museums

,!Name,Visitors in 2023 or 2022,City,Country
0,Louvre,"8,900,000 (2023)[1]",Paris,France
1,Vatican Museums,"6,800,000 (2023)[2]",Vatican City,Vatican
2,National Museum of China,"6,765,000 (2023)[3]",Beijing,China
3,British Museum,"5,820,860 (2023)[4]",London,United Kingdom
4,Natural History Museum,"5,688,608 (2023)[5]",London,United Kingdom
...,...,...,...,...
69,Palacio de Cristal del Retiro,"1,318,823[b][38]",Madrid,Spain
70,Museum of European and Mediterranean Civilisat...,"1,300,000 (2023)",Marseille,France
71,Scottish National Gallery,"1,277,230[38]",Edinburgh,United Kingdom
72,National Gallery Singapore,NaN,Singapore,Singapore
73,Museo Reina Sof√≠a,"1,253,183[c][38]",Madrid,Spain

In [ ]:
museums.columns

Index(['!Name', 'Visitors in 2023 or 2022', 'City', 'Country'], dtype='object')

In [ ]:
# Rename the first 2 columns

museums = museums.rename(columns = {'!Name': 'Name',
                                    'Visitors in 2023 or 2022': 'Visitors_2022_2023'
                                        })
museums

,Name,Visitors_2022_2023,City,Country
0,Louvre,"8,900,000 (2023)[1]",Paris,France
1,Vatican Museums,"6,800,000 (2023)[2]",Vatican City,Vatican
2,National Museum of China,"6,765,000 (2023)[3]",Beijing,China
3,British Museum,"5,820,860 (2023)[4]",London,United Kingdom
4,Natural History Museum,"5,688,608 (2023)[5]",London,United Kingdom
...,...,...,...,...
69,Palacio de Cristal del Retiro,"1,318,823[b][38]",Madrid,Spain
70,Museum of European and Mediterranean Civilisat...,"1,300,000 (2023)",Marseille,France
71,Scottish National Gallery,"1,277,230[38]",Edinburgh,United Kingdom
72,National Gallery Singapore,NaN,Singapore,Singapore
73,Museo Reina Sof√≠a,"1,253,183[c][38]",Madrid,Spain

In [ ]:
museums['Visitors_2022_2023'].str.split( r'[\(\[]', n=1)

0     [8,900,000 , 2023)[1]]
1     [6,800,000 , 2023)[2]]
2     [6,765,000 , 2023)[3]]
3     [5,820,860 , 2023)[4]]
4     [5,688,608 , 2023)[5]]
               ...
69       [1,318,823, b][38]]
70       [1,300,000 , 2023)]
71          [1,277,230, 38]]
72                       NaN
73       [1,253,183, c][38]]
Name: Visitors_2022_2023, Length: 74, dtype: object

In [ ]:
museums['Visitors_2022_2023'].str.split( r'[\(\[]', n=1).str[0]

0     8,900,000
1     6,800,000
2     6,765,000
3     5,820,860
4     5,688,608
         ...
69     1,318,823
70    1,300,000
71     1,277,230
72           NaN
73     1,253,183
Name: Visitors_2022_2023, Length: 74, dtype: object

In [ ]:
museums['Visitors(2022/2023)'] = museums['Visitors_2022_2023'].str.split( r'[\(\[]', n=1).str[0]
museums

,Name,Visitors_2022_2023,City,Country,Visitors(2022/2023)
0,Louvre,"8,900,000 (2023)[1]",Paris,France,"8,900,000"
1,Vatican Museums,"6,800,000 (2023)[2]",Vatican City,Vatican,"6,800,000"
2,National Museum of China,"6,765,000 (2023)[3]",Beijing,China,"6,765,000"
3,British Museum,"5,820,860 (2023)[4]",London,United Kingdom,"5,820,860"
4,Natural History Museum,"5,688,608 (2023)[5]",London,United Kingdom,"5,688,608"
...,...,...,...,...,...
69,Palacio de Cristal del Retiro,"1,318,823[b][38]",Madrid,Spain,"1,318,823"
70,Museum of European and Mediterranean Civilisat...,"1,300,000 (2023)",Marseille,France,"1,300,000"
71,Scottish National Gallery,"1,277,230[38]",Edinburgh,United Kingdom,"1,277,230"
72,National Gallery Singapore,NaN,Singapore,Singapore,NaN
73,Museo Reina Sof√≠a,"1,253,183[c][38]",Madrid,Spain,"1,253,183"

In [ ]:
museums = museums.drop(columns = ['Visitors_2022_2023'])
museums

,Name,City,Country,Visitors(2022/2023)
0,Louvre,Paris,France,"8,900,000"
1,Vatican Museums,Vatican City,Vatican,"6,800,000"
2,National Museum of China,Beijing,China,"6,765,000"
3,British Museum,London,United Kingdom,"5,820,860"
4,Natural History Museum,London,United Kingdom,"5,688,608"
...,...,...,...,...
69,Palacio de Cristal del Retiro,Madrid,Spain,"1,318,823"
70,Museum of European and Mediterranean Civilisat...,Marseille,France,"1,300,000"
71,Scottish National Gallery,Edinburgh,United Kingdom,"1,277,230"
72,National Gallery Singapore,Singapore,Singapore,NaN
73,Museo Reina Sof√≠a,Madrid,Spain,"1,253,183"

In [ ]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [ ]:
# Initiate the nominatim geocoder
geolocator = Nominatim(user_agent = 'monument_geocoder')

In [ ]:
# Create a rate limiter
geocode = RateLimiter(geolocator.geocode, min_delay_seconds = 1)

In [ ]:
test = geocode('Scottish National Gallery, Edinburgh,	United Kingdom')
test

Location(National Gallery, The Mound, Old Town, City of Edinburgh, Alba / Scotland, EH2 2EL, United Kingdom, (55.9508809, -3.195619300000002, 0.0))

In [ ]:
test.address

'National Gallery, The Mound, Old Town, City of Edinburgh, Alba / Scotland, EH2 2EL, United Kingdom'

In [ ]:
test.latitude

55.9508809

In [ ]:
test.longitude

-3.195619300000002

In [ ]:
test_2 = geocode('Palacio de Cristal del Retiro,	Madrid,	Spain')
test_2

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Palacio+de+Cristal+del+Retiro%2C%09Madrid%2C%09Spain&format=json&limit=1

Location(Estanque del Palacio de Cristal, Jer√≥nimos, Retiro, Madrid, Comunidad de Madrid, Espa√±a, (40.4137152, -3.6814084070038375, 0.0))

In [ ]:
museums['address_1'] = museums['Name'] +', ' + museums['City'] + ', '+ museums['Country']
museums

,Name,City,Country,Visitors(2022/2023),address_1
0,Louvre,Paris,France,"8,900,000","Louvre, Paris, France"
1,Vatican Museums,Vatican City,Vatican,"6,800,000","Vatican Museums, Vatican City, Vatican"
2,National Museum of China,Beijing,China,"6,765,000","National Museum of China, Beijing, China"
3,British Museum,London,United Kingdom,"5,820,860","British Museum, London, United Kingdom"
4,Natural History Museum,London,United Kingdom,"5,688,608","Natural History Museum, London, United Kingdom"
...,...,...,...,...,...
69,Palacio de Cristal del Retiro,Madrid,Spain,"1,318,823","Palacio de Cristal del Retiro, Madrid, Spain"
70,Museum of European and Mediterranean Civilisat...,Marseille,France,"1,300,000",Museum of European and Mediterranean Civilisat...
71,Scottish National Gallery,Edinburgh,United Kingdom,"1,277,230","Scottish National Gallery, Edinburgh, United K..."
72,National Gallery Singapore,Singapore,Singapore,NaN,"National Gallery Singapore, Singapore, Singapore"
73,Museo Reina Sof√≠a,Madrid,Spain,"1,253,183","Museo Reina Sof√≠a, Madrid, Spain"

In [ ]:
museums['Full address'] = 0
museums['Latitude'] = 0
museums['Longitude'] = 0

for index, row in museums.iterrows():
  # print(row['address_1'])
  addr = row['address_1']
  location_info = geocode(addr)

  try:

    # saving the address, lat, lon information into the corresponding variables during each iteration
    full_addres = location_info.address
    lat = location_info.latitude
    lon = location_info.longitude

    museums.loc[index, 'Full address' ] = full_addres
    museums.loc[index, 'Latitude' ] = lat
    museums.loc[index, 'Longitude' ] = lon

    print(f'We have gotten the data for {full_addres}')

  except AttributeError:
    museums.loc[index, 'Full address' ] = 'No Info'
    museums.loc[index, 'Latitude' ] = 'No Info'
    museums.loc[index, 'Longitude' ] = 'No Info'

<ipython-input-23-ac73c1ba7f76>:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Mus√©e du Louvre, Galerie V√©ro-Dodat, Quartier Les Halles, Paris 1er Arrondissement, Paris, √éle-de-France, France m√©tropolitaine, 75001, France' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  museums.loc[index, 'Full address' ] = full_addres
<ipython-input-23-ac73c1ba7f76>:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '48.8611473' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  museums.loc[index, 'Latitude' ] = lat
<ipython-input-23-ac73c1ba7f76>:19: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2.33802768704666' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  museums.loc[index, 'Longitude' ] = lon

We have gotten the data for Mus√©e du Louvre, Galerie V√©ro-Dodat, Quartier Les Halles, Paris 1er Arrondissement, Paris, √éle-de-France, France m√©tropolitaine, 75001, France
We have gotten the data for Musei Vaticani, Cortile Ottagono, Civitas Vaticana - Citt√† del Vaticano, 00120, Civitas Vaticana - Citt√† del Vaticano
We have gotten the data for ‰∏≠ÂõΩÂõΩÂÆ∂ÂçöÁâ©È¶Ü, 16, ‰∏úÈïøÂÆâË°ó, ‰∏úÂçéÈó®Ë°óÈÅì, È¶ñÈÉΩÂäüËÉΩÊ†∏ÂøÉÂå∫, ‰∏úÂüéÂå∫, Âåó‰∫¨Â∏Ç, 100006, ‰∏≠ÂõΩ
We have gotten the data for British Museum, Great Russell Street, Saint Giles, Bloomsbury, London Borough of Camden, London, Greater London, England, WC1B 3DG, United Kingdom
We have gotten the data for Natural History Museum, Cromwell Road, Brompton, Royal Borough of Kensington and Chelsea, London, Greater London, England, SW7 5BD, United Kingdom
We have gotten the data for The Metropolitan Museum of Art, 1000, 5th Avenue, Upper East Side, Manhattan, New York County, City of New York, New York, 10035, United States
We have gotten the data for American Museum of Natural History, 180, Central Park West, Manhattan Community Board 7, Manhattan, New York County, City of New York, New York, 10024, United States
We have gotten the data for ‰∏≠ÂõΩÁßëÂ≠¶ÊäÄÊúØÈ¶Ü, ÊπñÊôØ‰∏úË∑Ø, Â§ßÂ±ØË°óÈÅì, ÊúùÈò≥Âå∫, Âåó‰∫¨Â∏Ç, 100101, ‰∏≠ÂõΩ
We have gotten the data for Mus√©e d'Orsay, 1, Rue de la L√©gion d'Honneur, Quartier Saint-Thomas-d'Aquin, Paris 7e Arrondissement, Paris, √éle-de-France, France m√©tropolitaine, 75007, France
We have gotten the data for Âçó‰∫¨ÂçöÁâ©Èô¢, ‰∏≠Â±±‰∏úË∑Ø, Ê¢ÖÂõ≠Êñ∞ÊùëË°óÈÅì, ÁéÑÊ≠¶Âå∫, Âçó‰∫¨Â∏Ç, Ê±üËãèÁúÅ, 210018, ‰∏≠ÂõΩ

<ipython-input-23-ac73c1ba7f76>:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'No Info' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  museums.loc[index, 'Latitude' ] = 'No Info'
<ipython-input-23-ac73c1ba7f76>:26: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'No Info' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  museums.loc[index, 'Longitude' ] = 'No Info'

We have gotten the data for Tate Modern, Bankside, The Borough, London Borough of Southwark, London, Greater London, England, SE1 9TG, United Kingdom
We have gotten the data for National Museum of Natural History, 1000, Madison Drive Northwest, Ward 2, Washington, District of Columbia, 20560, United States
We have gotten the data for Íµ≠Î¶ΩÏ§ëÏïôÎ∞ïÎ¨ºÍ¥Ä, 137, ÏÑúÎπôÍ≥†Î°ú, Ïö©ÏÇ∞Îèô5Í∞Ä, ÏÑúÎπôÍ≥†Îèô, Ïö©ÏÇ∞Íµ¨, ÏÑúÏö∏ÌäπÎ≥ÑÏãú, 04386, ÎåÄÌïúÎØºÍµ≠
We have gotten the data for Âπø‰∏úÁúÅÂçöÁâ©È¶Ü, 2Âè∑, Áè†Ê±ü‰∏úË∑Ø, ÁåéÂæ∑Ë°óÈÅì, Â§©Ê≤≥Âå∫, ÂπøÂ∑ûÂ∏Ç, Âπø‰∏úÁúÅ, 510623, ‰∏≠ÂõΩ
We have gotten the data for –ì–æ—Å—É–¥–∞—Ä—Å—Ç–≤–µ–Ω–Ω—ã–π –≠—Ä–º–∏—Ç–∞–∂, –ú–∏–ª–ª–∏–æ–Ω–Ω–∞—è —É–ª–∏—Ü–∞, –î–≤–æ—Ä—Ü–æ–≤—ã–π –æ–∫—Ä—É–≥, –°–∞–Ω–∫—Ç-–ü–µ—Ç–µ—Ä–±—É—Ä–≥, –°–µ–≤–µ—Ä–æ-–ó–∞–ø–∞–¥–Ω—ã–π —Ñ–µ–¥–µ—Ä–∞–ª—å–Ω—ã–π –æ–∫—Ä—É–≥, 191186, –†–æ—Å—Å–∏—è
We have gotten the data for Museo del Prado, Paseo del Prado, Jer√≥nimos, Retiro, Madrid, Comunidad de Madrid, 28014, Espa√±a
We have gotten the data for Victoria and Albert Museum, Cromwell Road, Brompton, Royal Borough of Kensington and Chelsea, London, Greater London, England, SW7 2RL, United Kingdom
We have gotten the data for National Gallery, St. Martin's Place, Seven Dials, Bloomsbury, London, Greater London, England, WC2N 5DN, United Kingdom
We have gotten the data for MoMA, 11, West 53rd Street, Manhattan Community Board 5, Manhattan, New York County, City of New York, New York, 10019, United States
We have gotten the data for Galleria degli Uffizi, 6, Piazzale degli Uffizi, Oltrarno, Quartiere 1, Firenze, Toscana, 50122, Italia
We have gotten the data for Museo Nacional de Historia Castillo de Chapultepec, Peatonal del Cerro, 1a. Secci√≥n del Bosque de Chapultepec, Ciudad de M√©xico, Miguel Hidalgo, Ciudad de M√©xico, 11580, M√©xico
We have gotten the data for Museo Guggenheim Bilbao, 2, Lehendakari Leizaola Kalea, Indautxu, Abando, Bilbao, Bizkaia, Euskadi, 48009, Espa√±a
We have gotten the data for Mevl√¢na M√ºzesi, Aslanlƒ± Kƒ±≈üla Caddesi, Aziziye Mahallesi, Karatay, Konya, ƒ∞√ß Anadolu B√∂lgesi, 42200, T√ºrkiye
We have gotten the data for M+, 38, ÂçöÁâ©È§®ÈÅì Museum Drive, Ë•ø‰πùÈæç West Kowloon, Ê≤πÈ∫ªÂú∞ Yau Ma Tei, Ê≤πÂ∞ñÊó∫ÂçÄ Yau Tsim Mong District, ‰πùÈæç Kowloon, È¶ôÊ∏Ø Hong Kong, 000000, ‰∏≠ÂõΩ
We have gotten the data for Nanno, Ville d'Anaunia, Comunit√† della Val di Non, Provincia di Trento, Trentino-Alto Adige/S√ºdtirol, 38093, Italia
We have gotten the data for Topographie des Terrors, 8, Niederkirchnerstra√üe, Mitte, Berlin, 10963, Deutschland
We have gotten the data for È∏¶ÁâáÊàò‰∫âÂçöÁâ©È¶Ü, Ëß£ÊîæË∑Ø, ËôéÈó®Èïá, ‰∏úËéûÂ∏Ç, Âπø‰∏úÁúÅ, 523061, ‰∏≠ÂõΩ
We have gotten the data for Cit√© des Sciences et de l'Industrie, Galerie de la Villette, Quartier du Pont-de-Flandre, Paris 19e Arrondissement, Paris, √éle-de-France, France m√©tropolitaine, 75019, France
We have gotten the data for National Museum of Scotland, Chambers Street, Old Town, City of Edinburgh, Alba / Scotland, EH1 1JF, United Kingdom
We have gotten the data for –¢—Ä–µ—Ç—å—è–∫–æ–≤—Å–∫–∞—è –≥–∞–ª–µ—Ä–µ—è, 10, –õ–∞–≤—Ä—É—à–∏–Ω—Å–∫–∏–π –ø–µ—Ä–µ—É–ª–æ–∫, —Ä–∞–π–æ–Ω –Ø–∫–∏–º–∞–Ω–∫–∞, –ú–æ—Å–∫–≤–∞, –¶–µ–Ω—Ç—Ä–∞–ª—å–Ω—ã–π —Ñ–µ–¥–µ—Ä–∞–ª—å–Ω—ã–π –æ–∫—Ä—É–≥, 119017, –†–æ—Å—Å–∏—è
We have gotten the data for ÂúãÁ´ãÁßëÂ≠∏Â∑•ËóùÂçöÁâ©È§®, 720, ‰πùÂ¶Ç‰∏ÄË∑Ø, ÂÆâÁôºÈáå, ‰∏âÊ∞ëÂçÄ, Â§ßÊ∏Ø, È´òÈõÑÂ∏Ç, 807, Ëá∫ÁÅ£
We have gotten the data for Íµ≠Î¶ΩÌòÑÎåÄÎØ∏Ïà†Í¥Ä ÏÑúÏö∏Í¥Ä, 30, ÏÇºÏ≤≠Î°ú, Ï∞ΩÏÑ±Îèô, ÏÇºÏ≤≠Îèô, Ï¢ÖÎ°úÍµ¨, ÏÑúÏö∏ÌäπÎ≥ÑÏãú, 03045, ÎåÄÌïúÎØºÍµ≠
We have gotten the data for Rijksmuseum, Paulus Potterstraat, Oud-Zuid, Zuid, Amsterdam, Noord-Holland, Nederland, 1071 ZB, Nederland
We have gotten the data for California Science Center, 700, Exposition Park Drive, Exposition Park, Los Angeles, Los Angeles County, California, 90037, United States
We have gotten the data for Âçó‰∫¨ÂçöÁâ©Èô¢, ‰∏≠Â±±‰∏úË∑Ø, Ê¢ÖÂõ≠Êñ∞ÊùëË°óÈÅì, ÁéÑÊ≠¶Âå∫, Âçó‰∫¨Â∏Ç, Ê±üËãèÁúÅ, 210018, ‰∏≠ÂõΩ
We have gotten the data for National Gallery of Victoria, 130-180, St Kilda Road, Southbank, Melbourne, City of Melbourne, Victoria, 3006, Australia
We have gotten the data for Âª∫Â∑ùÂçöÁâ©È¶ÜËÅöËêΩ, Â§ßÊñ∞Ë∑Ø, Â§ßÈÇëÂéø, ÊàêÈÉΩÂ∏Ç, ÂõõÂ∑ùÁúÅ, ‰∏≠ÂõΩ
We have gotten the data for Houston Museum of Natural Science, 5555, Hermann Park Drive, Houston, Harris County, Texas, 77030, United States
We have gotten the data for Êù±‰∫¨ÈÉΩÁæéË°ìÈ§®, Á•ûÁî∞ÁôΩÂ±±Á∑ö, ‰∏äÈáé‰∏É‰∏ÅÁõÆ, Âè∞Êù±Âå∫, Êù±‰∫¨ÈÉΩ, 110-8714, Êó•Êú¨
We have gotten the data for Â∏∏Â∑ûÂçöÁâ©È¶Ü, ÂπøÂú∫Â§ßÈÅì, ‰∏â‰∫ïÁ§æÂå∫, ‰∏â‰∫ïË°óÈÅì, Êñ∞ÂåóÂå∫, Â∏∏Â∑ûÂ∏Ç, Ê±üËãèÁúÅ, 213000, ‰∏≠ÂõΩ
We have gotten the data for Humboldt Forum, Schlo√üplatz, Friedrichswerder, Mitte, Berlin, 10178, Deutschland
We have gotten the data for È´òÈõÑÂ∏ÇÁ´ãÁæéË°ìÈ§®, 80, ÁæéË°ìÈ§®Ë∑Ø, ÈæçÊ∞¥Èáå, ÈºìÂ±±ÂçÄ, È´òÈõÑÂ∏Ç, 80460, Ëá∫ÁÅ£
We have gotten the data for ŒúŒøœÖœÉŒµŒØŒø ŒëŒ∫œÅœåœÄŒøŒªŒ∑œÇ, 15, ŒîŒπŒøŒΩœÖœÉŒØŒøœÖ ŒëœÅŒµŒøœÄŒ±Œ≥ŒØœÑŒøœÖ, ŒëœÉœÑŒµœÅŒøœÉŒ∫ŒøœÄŒµŒØŒø, ŒëœÉœçœÅŒºŒ±œÑŒøœÇ, Œ†ŒµœÑœÅŒ¨ŒªœâŒΩŒ±, 1Œ∑ ŒöŒøŒπŒΩœåœÑŒ∑œÑŒ± ŒëŒ∏Œ∑ŒΩœéŒΩ, ŒëŒ∏ŒÆŒΩŒ±, ŒîŒÆŒºŒøœÇ ŒëŒ∏Œ∑ŒΩŒ±ŒØœâŒΩ, Œ†ŒµœÅŒπœÜŒµœÅŒµŒπŒ±Œ∫ŒÆ ŒïŒΩœåœÑŒ∑œÑŒ± ŒöŒµŒΩœÑœÅŒπŒ∫Œøœç Œ§ŒøŒºŒ≠Œ± ŒëŒ∏Œ∑ŒΩœéŒΩ, Œ†ŒµœÅŒπœÜŒ≠œÅŒµŒπŒ± ŒëœÑœÑŒπŒ∫ŒÆœÇ, ŒëœÄŒøŒ∫ŒµŒΩœÑœÅœâŒºŒ≠ŒΩŒ∑ ŒîŒπŒøŒØŒ∫Œ∑œÉŒ∑ ŒëœÑœÑŒπŒ∫ŒÆœÇ, 117 42, ŒïŒªŒªŒ¨œÇ
We have gotten the data for ‰∏≠ÂõΩÁßëÂ≠¶ÊäÄÊúØÈ¶Ü, ÊπñÊôØ‰∏úË∑Ø, Â§ßÂ±ØË°óÈÅì, ÊúùÈò≥Âå∫, Âåó‰∫¨Â∏Ç, 100101, ‰∏≠ÂõΩ
We have gotten the data for Galleria dell'Accademia, 58/60, Via Ricasoli, Quartiere 1, Firenze, Toscana, 50122, Italia
We have gotten the data for ËãèÂ∑ûÂçöÁâ©È¶Ü, Â∞èÈ£ûËôπÊ°•, ÊãôÊîøÂõ≠Á§æÂå∫, Âπ≥Ê±üË°óÈÅì, ÂßëËãèÂå∫, ËãèÂ∑ûÂ∏Ç, Ê±üËãèÁúÅ, 215001, ‰∏≠ÂõΩ

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Chengdu+Museum%2C+Chengdu%2C+China&format=json&limit=1

We have gotten the data for Â§ßÁÜäÁå´ÂçöÁâ©È¶Ü, 1375, ÁÜäÁå´Â§ßÈÅì, ÁôΩËé≤Ê±†Ë°óÈÅì, ÊàêÂçéÂå∫, ÊàêÈÉΩÂ∏Ç, ÈáëÁâõÂå∫, ÂõõÂ∑ùÁúÅ, 610081, ‰∏≠ÂõΩ
We have gotten the data for ‰∏äÊµ∑ÁßëÊäÄÈ¶Ü, 2000, ‰∏ñÁ∫™Â§ßÈÅì, Ëä±Êú®Ë°óÈÅì, ‰∏•Ê°•, Êµ¶‰∏úÊñ∞Âå∫, ‰∏äÊµ∑Â∏Ç, 200127, ‰∏≠ÂõΩ
We have gotten the data for ÂõΩÁ´ãÊñ∞ÁæéË°ìÈ§®, 2, ÂÖ≠Êú¨Êú®‰∏É‰∏ÅÁõÆ, ÂÖ≠Êú¨Êú®, È∫ªÂ∏É, Ê∏ØÂå∫, Êù±‰∫¨ÈÉΩ, 106-8558, Êó•Êú¨
We have gotten the data for Êù±‰∫¨ÂõΩÁ´ãÂçöÁâ©È§®, Âè∞Êù±Âå∫, Êù±‰∫¨ÈÉΩ, 110-8712, Êó•Êú¨
We have gotten the data for Muzeum Narodowe w Krakowie, 1, Aleja 3 Maja, B≈Çonia, Zwierzyniec, Krak√≥w, wojew√≥dztwo ma≈Çopolskie, 30-062, Polska
We have gotten the data for Centro Cultural Banco do Brasil S√£o Paulo, 112, Rua √Ålvares Penteado, Glic√©rio, S√©, S√£o Paulo, Regi√£o Imediata de S√£o Paulo, Regi√£o Metropolitana de S√£o Paulo, Regi√£o Geogr√°fica Intermedi√°ria de S√£o Paulo, S√£o Paulo, Regi√£o Sudeste, 01012-000, Brasil
We have gotten the data for Van Gogh Museum, 7, Paulus Potterstraat, Oud-Zuid, Zuid, Amsterdam, Noord-Holland, Nederland, 1071 CX, Nederland
We have gotten the data for ÂõΩÁ´ãÁßëÂ≠¶ÂçöÁâ©È§®, Âè∞Êù±Âå∫, Êù±‰∫¨ÈÉΩ, 110-8718, Êó•Êú¨
We have gotten the data for Kunsthistorisches Museum, 5, Burgring, K√§rntner Viertel, Innere Stadt, Wien, 1010, √ñsterreich
We have gotten the data for Museo Nazionale di Castel Sant‚ÄôAngelo, 50, Lungotevere Castello, Borgo, Municipio Roma I, Roma, Roma Capitale, Lazio, 00193, Italia
We have gotten the data for Estanque del Palacio de Cristal, Jer√≥nimos, Retiro, Madrid, Comunidad de Madrid, Espa√±a
We have gotten the data for National Gallery, The Mound, Old Town, City of Edinburgh, Alba / Scotland, EH2 2EL, United Kingdom
We have gotten the data for National Gallery Singapore, 1, Saint Andrew's Road, Civic District, Downtown Core, Central, Singapore, 178957, Singapore
We have gotten the data for Museo Nacional Centro de Arte Reina Sof√≠a, 52, Calle de Santa Isabel, Lavapi√©s, Embajadores, Centro, Madrid, Comunidad de Madrid, 28012, Espa√±a

In [ ]:
museums

,Name,City,Country,Visitors(2022/2023),address_1,Full address,Latitude,Longitude
0,Louvre,Paris,France,"8,900,000","Louvre, Paris, France","Mus√©e du Louvre, Galerie V√©ro-Dodat, Quartier ...",48.861147,2.338028
1,Vatican Museums,Vatican City,Vatican,"6,800,000","Vatican Museums, Vatican City, Vatican","Musei Vaticani, Cortile Ottagono, Civitas Vati...",41.904961,12.454662
2,National Museum of China,Beijing,China,"6,765,000","National Museum of China, Beijing, China","‰∏≠ÂõΩÂõΩÂÆ∂ÂçöÁâ©È¶Ü, 16, ‰∏úÈïøÂÆâË°ó, ‰∏úÂçéÈó®Ë°óÈÅì, È¶ñÈÉΩÂäüËÉΩÊ†∏ÂøÉÂå∫, ‰∏úÂüéÂå∫, Âåó‰∫¨Â∏Ç, 1...",39.903746,116.39539
3,British Museum,London,United Kingdom,"5,820,860","British Museum, London, United Kingdom","British Museum, Great Russell Street, Saint Gi...",51.519294,-0.128018
4,Natural History Museum,London,United Kingdom,"5,688,608","Natural History Museum, London, United Kingdom","Natural History Museum, Cromwell Road, Brompto...",51.496511,-0.176002
...,...,...,...,...,...,...,...,...
69,Palacio de Cristal del Retiro,Madrid,Spain,"1,318,823","Palacio de Cristal del Retiro, Madrid, Spain","Estanque del Palacio de Cristal, Jer√≥nimos, Re...",40.413715,-3.681408
70,Museum of European and Mediterranean Civilisat...,Marseille,France,"1,300,000",Museum of European and Mediterranean Civilisat...,No Info,No Info,No Info
71,Scottish National Gallery,Edinburgh,United Kingdom,"1,277,230","Scottish National Gallery, Edinburgh, United K...","National Gallery, The Mound, Old Town, City of...",55.950881,-3.195619
72,National Gallery Singapore,Singapore,Singapore,NaN,"National Gallery Singapore, Singapore, Singapore","National Gallery Singapore, 1, Saint Andrew's ...",1.290256,103.851471
73,Museo Reina Sof√≠a,Madrid,Spain,"1,253,183","Museo Reina Sof√≠a, Madrid, Spain","Museo Nacional Centro de Arte Reina Sof√≠a, 52,...",40.40805,-3.694422

In [ ]:
museums[museums['Full address'].str.contains('No Info', na = False)]

,Name,City,Country,Visitors(2022/2023),address_1,Full address,Latitude,Longitude
10,Suzhou Museum,"Suzhou, China",China,"4,852,000","Suzhou Museum, Suzhou, China, China",No Info,No Info,No Info
15,Mus√©e National d'Histoire Naturelle,Paris,France,3.8 million,"Mus√©e National d'Histoire Naturelle, Paris, Fr...",No Info,No Info,No Info
19,National Air and Space Museum[a],"Washington, D.C.",United States,"3,100,000","National Air and Space Museum[a], Washington, ...",No Info,No Info,No Info
23,National Museum of Anthropology,Mexico City,Mexico,"2,636,352","National Museum of Anthropology, Mexico City, ...",No Info,No Info,No Info
25,Smithsonian Museum of American History,"Washington, D.C.",United States,"2,100,000","Smithsonian Museum of American History, Washin...",No Info,No Info,No Info
28,State Russian Museum,Saint Petersburg,Russia,"2,900,000","State Russian Museum, Saint Petersburg, Russia",No Info,No Info,No Info
29,National Museum of Marine Science and Technology,Keelung,Taiwan,"2,726,000",National Museum of Marine Science and Technolo...,No Info,No Info,No Info
30,London Science Museum,London,United Kingdom,"2,957,000","London Science Museum, London, United Kingdom",No Info,No Info,No Info
32,Chinese Aviation Museum,Beijing,China,"2,300,000","Chinese Aviation Museum, Beijing, China",No Info,No Info,No Info
43,Royal Museums Greenwich,London,United Kingdom,"1,628,580","Royal Museums Greenwich, London, United Kingdom",No Info,No Info,No Info
45,Zhejiang Museum of Natural History,Hangzhou,China,"1,581,263","Zhejiang Museum of Natural History, Hangzhou, ...",No Info,No Info,No Info
60,Louis Vuitton Foundation,Paris,France,"1,500,000","Louis Vuitton Foundation, Paris, France",No Info,No Info,No Info
68,Tianjin Natural History Museum,Tianjin,China,"1,320,752","Tianjin Natural History Museum, Tianjin, China",No Info,No Info,No Info
70,Museum of European and Mediterranean Civilisat...,Marseille,France,"1,300,000",Museum of European and Mediterranean Civilisat...,No Info,No Info,No Info

In [ ]:
museums = museums[~museums['Full address'].str.contains('No Info', na = False)]
museums

,Name,City,Country,Visitors(2022/2023),address_1,Full address,Latitude,Longitude
0,Louvre,Paris,France,"8,900,000","Louvre, Paris, France","Mus√©e du Louvre, Galerie V√©ro-Dodat, Quartier ...",48.861147,2.338028
1,Vatican Museums,Vatican City,Vatican,"6,800,000","Vatican Museums, Vatican City, Vatican","Musei Vaticani, Cortile Ottagono, Civitas Vati...",41.904961,12.454662
2,National Museum of China,Beijing,China,"6,765,000","National Museum of China, Beijing, China","‰∏≠ÂõΩÂõΩÂÆ∂ÂçöÁâ©È¶Ü, 16, ‰∏úÈïøÂÆâË°ó, ‰∏úÂçéÈó®Ë°óÈÅì, È¶ñÈÉΩÂäüËÉΩÊ†∏ÂøÉÂå∫, ‰∏úÂüéÂå∫, Âåó‰∫¨Â∏Ç, 1...",39.903746,116.39539
3,British Museum,London,United Kingdom,"5,820,860","British Museum, London, United Kingdom","British Museum, Great Russell Street, Saint Gi...",51.519294,-0.128018
4,Natural History Museum,London,United Kingdom,"5,688,608","Natural History Museum, London, United Kingdom","Natural History Museum, Cromwell Road, Brompto...",51.496511,-0.176002
5,Metropolitan Museum of Art,New York City,United States,"5,400,000","Metropolitan Museum of Art, New York City, Uni...","The Metropolitan Museum of Art, 1000, 5th Aven...",40.77944,-73.963382
6,American Museum of Natural History,New York City,United States|,"5,400,000","American Museum of Natural History, New York C...","American Museum of Natural History, 180, Centr...",40.781101,-73.974236
7,China Science and Technology Museum,Beijing,China,"5,315,000","China Science and Technology Museum, Beijing, ...","‰∏≠ÂõΩÁßëÂ≠¶ÊäÄÊúØÈ¶Ü, ÊπñÊôØ‰∏úË∑Ø, Â§ßÂ±ØË°óÈÅì, ÊúùÈò≥Âå∫, Âåó‰∫¨Â∏Ç, 100101, ‰∏≠ÂõΩ",40.004625,116.39244
8,Mus√©e d'Orsay,Paris,France,5.2 million,"Mus√©e d'Orsay, Paris, France","Mus√©e d'Orsay, 1, Rue de la L√©gion d'Honneur, ...",48.859918,2.326585
9,Nanjing Museum,Nanjing,China,"5,007,000","Nanjing Museum, Nanjing, China","Âçó‰∫¨ÂçöÁâ©Èô¢, ‰∏≠Â±±‰∏úË∑Ø, Ê¢ÖÂõ≠Êñ∞ÊùëË°óÈÅì, ÁéÑÊ≠¶Âå∫, Âçó‰∫¨Â∏Ç, Ê±üËãèÁúÅ, 210018, ‰∏≠ÂõΩ",32.042299,118.819887
11,Tate Modern,London,United Kingdom,"4,742,038","Tate Modern, London, United Kingdom","Tate Modern, Bankside, The Borough, London Bor...",51.507429,-0.099342
12,National Museum of Natural History,"Washington, D.C.",United States,"4,400,000","National Museum of Natural History, Washington...","National Museum of Natural History, 1000, Madi...",38.891245,-77.02597
13,National Museum of Korea,Seoul,South Korea,4.18 million,"National Museum of Korea, Seoul, South Korea","Íµ≠Î¶ΩÏ§ëÏïôÎ∞ïÎ¨ºÍ¥Ä, 137, ÏÑúÎπôÍ≥†Î°ú, Ïö©ÏÇ∞Îèô5Í∞Ä, ÏÑúÎπôÍ≥†Îèô, Ïö©ÏÇ∞Íµ¨, ÏÑúÏö∏ÌäπÎ≥ÑÏãú, 0...",37.523953,126.98032
14,Guangdong Museum,Guangzhou,China,"4,000,000","Guangdong Museum, Guangzhou, China","Âπø‰∏úÁúÅÂçöÁâ©È¶Ü, 2Âè∑, Áè†Ê±ü‰∏úË∑Ø, ÁåéÂæ∑Ë°óÈÅì, Â§©Ê≤≥Âå∫, ÂπøÂ∑ûÂ∏Ç, Âπø‰∏úÁúÅ, 510623, ‰∏≠ÂõΩ",23.1174,113.321416
16,State Hermitage Museum,Saint Petersburg,Russia,"3,273,753","State Hermitage Museum, Saint Petersburg, Russia","–ì–æ—Å—É–¥–∞—Ä—Å—Ç–≤–µ–Ω–Ω—ã–π –≠—Ä–º–∏—Ç–∞–∂, –ú–∏–ª–ª–∏–æ–Ω–Ω–∞—è —É–ª–∏—Ü–∞, –î–≤–æ...",59.941208,30.315487
17,Prado Museum,Madrid,Spain,"3,338,285","Prado Museum, Madrid, Spain","Museo del Prado, Paseo del Prado, Jer√≥nimos, R...",40.413793,-3.692038
18,Victoria and Albert Museum,London,United Kingdom,"3,110,000","Victoria and Albert Museum, London, United Kin...","Victoria and Albert Museum, Cromwell Road, Bro...",51.496884,-0.171637
20,National Gallery,London,United Kingdom,"3,096,508","National Gallery, London, United Kingdom","National Gallery, St. Martin's Place, Seven Di...",51.508881,-0.128383
21,Museum of Modern Art,New York City,United States,"2,839,509","Museum of Modern Art, New York City, United St...","MoMA, 11, West 53rd Street, Manhattan Communit...",40.761612,-73.977499
22,Galleria degli Uffizi,Florence,Italia,"2,717,857","Galleria degli Uffizi, Florence, Italia","Galleria degli Uffizi, 6, Piazzale degli Uffiz...",43.768313,11.255801
24,Museo Nacional de Historia,Mexico City,Mexico,"2,456,825","Museo Nacional de Historia, Mexico City, Mexico",Museo Nacional de Historia Castillo de Chapult...,19.420463,-99.182087
26,Guggenheim Museum Bilbao,Bilbao,Spain,"1,324,000","Guggenheim Museum Bilbao, Bilbao, Spain","Museo Guggenheim Bilbao, 2, Lehendakari Leizao...",43.268428,-2.934061
27,Mevlana Museum,Konya,Turkey,"3,352,505","Mevlana Museum, Konya, Turkey","Mevl√¢na M√ºzesi, Aslanlƒ± Kƒ±≈üla Caddesi, Aziziye...",37.870665,32.504965
31,M+,Hong Kong,Hong Kong,"2,798,000","M+, Hong Kong, Hong Kong","M+, 38, ÂçöÁâ©È§®ÈÅì Museum Drive, Ë•ø‰πùÈæç West Kowloon, Ê≤π...",22.301043,114.159154
33,National Museum of Natural Science,Taiwan,NaN,"2,738,000",NaN,"Nanno, Ville d'Anaunia, Comunit√† della Val di ...",46.314475,11.048029
34,Topography of Terror,Berlin,Germany,"2,100,000","Topography of Terror, Berlin, Germany","Topographie des Terrors, 8, Niederkirchnerstra...",52.5063,13.384016
35,Opium War Museum,Dongguan,China,"2,025,800","Opium War Museum, Dongguan, China","È∏¶ÁâáÊàò‰∫âÂçöÁâ©È¶Ü, Ëß£ÊîæË∑Ø, ËôéÈó®Èïá, ‰∏úËéûÂ∏Ç, Âπø‰∏úÁúÅ, 523061, ‰∏≠ÂõΩ",22.828141,113.654557
36,Cit√© des Sciences et de l'Industrie,Paris,France,"1,992,823","Cit√© des Sciences et de l'Industrie, Paris, Fr...","Cit√© des Sciences et de l'Industrie, Galerie d...",48.895678,2.387967
37,National Museum of Scotland,Edinburgh,United Kingdom,"1,973,751","National Museum of Scotland, Edinburgh, United...","National Museum of Scotland, Chambers Street, ...",55.947071,-3.189336
38,State Tretyakov Gallery,Moscow,Russia,"1,910,000","State Tretyakov Gallery, Moscow, Russia","–¢—Ä–µ—Ç—å—è–∫–æ–≤—Å–∫–∞—è –≥–∞–ª–µ—Ä–µ—è, 10, –õ–∞–≤—Ä—É—à–∏–Ω—Å–∫–∏–π –ø–µ—Ä–µ—É–ª...",55.741361,37.62022
39,National Science and Technology Museum,Kaohsiung,Taiwan,"1,875,372","National Science and Technology Museum, Kaohsi...","ÂúãÁ´ãÁßëÂ≠∏Â∑•ËóùÂçöÁâ©È§®, 720, ‰πùÂ¶Ç‰∏ÄË∑Ø, ÂÆâÁôºÈáå, ‰∏âÊ∞ëÂçÄ, Â§ßÊ∏Ø, È´òÈõÑÂ∏Ç, 807, Ëá∫ÁÅ£",22.6416,120.322686
40,National Museum of Modern and Contemporary Art,Seoul,South Korea,"1,806,641",National Museum of Modern and Contemporary Art...,"Íµ≠Î¶ΩÌòÑÎåÄÎØ∏Ïà†Í¥Ä ÏÑúÏö∏Í¥Ä, 30, ÏÇºÏ≤≠Î°ú, Ï∞ΩÏÑ±Îèô, ÏÇºÏ≤≠Îèô, Ï¢ÖÎ°úÍµ¨, ÏÑúÏö∏ÌäπÎ≥ÑÏãú, 03...",37.578865,126.98068
41,Rijksmuseum,Amsterdam,Netherlands,"1,766,084","Rijksmuseum, Amsterdam, Netherlands","Rijksmuseum, Paulus Potterstraat, Oud-Zuid, Zu...",52.359849,4.885039
42,California Science Center,Los Angeles,United States,"1,694,000","California Science Center, Los Angeles, United...","California Science Center, 700, Exposition Par...",34.015976,-118.286287
44,Nanjing Museum,Nanjing,China,"1,610,000","Nanjing Museum, Nanjing, China","Âçó‰∫¨ÂçöÁâ©Èô¢, ‰∏≠Â±±‰∏úË∑Ø, Ê¢ÖÂõ≠Êñ∞ÊùëË°óÈÅì, ÁéÑÊ≠¶Âå∫, Âçó‰∫¨Â∏Ç, Ê±üËãèÁúÅ, 210018, ‰∏≠ÂõΩ",32.042299,118.819887
46,National Gallery of Victoria,Melbourne,Australia,"1,580,303","National Gallery of Victoria, Melbourne, Austr...","National Gallery of Victoria, 130-180, St Kild...",-37.822926,144.968656
47,Jianchuan Museum Cluster,Chengdu,China,"1,538,143","Jianchuan Museum Cluster, Chengdu, China","Âª∫Â∑ùÂçöÁâ©È¶ÜËÅöËêΩ, Â§ßÊñ∞Ë∑Ø, Â§ßÈÇëÂéø, ÊàêÈÉΩÂ∏Ç, ÂõõÂ∑ùÁúÅ, ‰∏≠ÂõΩ",30.502445,103.617669
48,Houston Museum of Natural Science,Houston,United States,"1,520,000","Houston Museum of Natural Science, Houston, Un...","Houston Museum of Natural Science, 5555, Herma...",29.722123,-95.389936
49,Tokyo Metropolitan Art Museum,Tokyo,Japan,"1,509,970","Tokyo Metropolitan Art Museum, Tokyo, Japan","Êù±‰∫¨ÈÉΩÁæéË°ìÈ§®, Á•ûÁî∞ÁôΩÂ±±Á∑ö, ‰∏äÈáé‰∏É‰∏ÅÁõÆ, Âè∞Êù±Âå∫, Êù±‰∫¨ÈÉΩ, 110-8714, Êó•Êú¨",35.717106,139.773146
50,Changzhou Museum,Changzhou,China,"1,508,229","Changzhou Museum, Changzhou, China","Â∏∏Â∑ûÂçöÁâ©È¶Ü, ÂπøÂú∫Â§ßÈÅì, ‰∏â‰∫ïÁ§æÂå∫, ‰∏â‰∫ïË°óÈÅì, Êñ∞ÂåóÂå∫, Â∏∏Â∑ûÂ∏Ç, Ê±üËãèÁúÅ, 213000...",31.811045,119.966857
51,Humboldt Forum,Berlin,Germany,"1,500,000","Humboldt Forum, Berlin, Germany","Humboldt Forum, Schlo√üplatz, Friedrichswerder,...",52.517032,13.401227
52,Kaohsiung Museum of Fine Arts,Kaohsiung,Taiwan,"1,461,406","Kaohsiung Museum of Fine Arts, Kaohsiung, Taiwan","È´òÈõÑÂ∏ÇÁ´ãÁæéË°ìÈ§®, 80, ÁæéË°ìÈ§®Ë∑Ø, ÈæçÊ∞¥Èáå, ÈºìÂ±±ÂçÄ, È´òÈõÑÂ∏Ç, 80460, Ëá∫ÁÅ£",22.656511,120.286174
53,Acropolis Museum,Athens,Greece,"1,451,727","Acropolis Museum, Athens, Greece","ŒúŒøœÖœÉŒµŒØŒø ŒëŒ∫œÅœåœÄŒøŒªŒ∑œÇ, 15, ŒîŒπŒøŒΩœÖœÉŒØŒøœÖ ŒëœÅŒµŒøœÄŒ±Œ≥ŒØœÑŒøœÖ, ...",37.968533,23.728471
54,China Science and Technology Museum,Beijing,China,"1,431,189","China Science and Technology Museum, Beijing, ...","‰∏≠ÂõΩÁßëÂ≠¶ÊäÄÊúØÈ¶Ü, ÊπñÊôØ‰∏úË∑Ø, Â§ßÂ±ØË°óÈÅì, ÊúùÈò≥Âå∫, Âåó‰∫¨Â∏Ç, 100101, ‰∏≠ÂõΩ",40.004625,116.39244
55,Galleria dell'Accademia,Florence,Italy,"1,428,369","Galleria dell'Accademia, Florence, Italy","Galleria dell'Accademia, 58/60, Via Ricasoli, ...",43.776917,11.258758
56,Suzhou Museum,Suzhou,China,"1,417,412","Suzhou Museum, Suzhou, China","ËãèÂ∑ûÂçöÁâ©È¶Ü, Â∞èÈ£ûËôπÊ°•, ÊãôÊîøÂõ≠Á§æÂå∫, Âπ≥Ê±üË°óÈÅì, ÂßëËãèÂå∫, ËãèÂ∑ûÂ∏Ç, Ê±üËãèÁúÅ, 21500...",31.325417,120.623093
57,Chengdu Museum,Chengdu,China,"1,404,735","Chengdu Museum, Chengdu, China","Â§ßÁÜäÁå´ÂçöÁâ©È¶Ü, 1375, ÁÜäÁå´Â§ßÈÅì, ÁôΩËé≤Ê±†Ë°óÈÅì, ÊàêÂçéÂå∫, ÊàêÈÉΩÂ∏Ç, ÈáëÁâõÂå∫, ÂõõÂ∑ùÁúÅ,...",30.73586,104.144022
58,Shanghai Science and Technology Museum,Shanghai,China,"1,403,179","Shanghai Science and Technology Museum, Shangh...","‰∏äÊµ∑ÁßëÊäÄÈ¶Ü, 2000, ‰∏ñÁ∫™Â§ßÈÅì, Ëä±Êú®Ë°óÈÅì, ‰∏•Ê°•, Êµ¶‰∏úÊñ∞Âå∫, ‰∏äÊµ∑Â∏Ç, 200127...",31.220602,121.536733
59,"The National Art Center, Tokyo",Tokyo,Japan,"1,400,096","The National Art Center, Tokyo, Tokyo, Japan","ÂõΩÁ´ãÊñ∞ÁæéË°ìÈ§®, 2, ÂÖ≠Êú¨Êú®‰∏É‰∏ÅÁõÆ, ÂÖ≠Êú¨Êú®, È∫ªÂ∏É, Ê∏ØÂå∫, Êù±‰∫¨ÈÉΩ, 106-8558, Êó•Êú¨",35.665347,139.726443
61,Tokyo National Museum,Tokyo,Japan,"1,372,132","Tokyo National Museum, Tokyo, Japan","Êù±‰∫¨ÂõΩÁ´ãÂçöÁâ©È§®, Âè∞Êù±Âå∫, Êù±‰∫¨ÈÉΩ, 110-8712, Êó•Êú¨",35.719045,139.775968
62,National Museum in Krak√≥w,Krak√≥w,Poland,"1,365,425","National Museum in Krak√≥w, Krak√≥w, Poland","Muzeum Narodowe w Krakowie, 1, Aleja 3 Maja, B...",50.060456,19.923601
63,Centro Cultural Banco do Brasil,S√£o Paulo,Brazil,"1,364,208","Centro Cultural Banco do Brasil, S√£o Paulo, Br...","Centro Cultural Banco do Brasil S√£o Paulo, 112...",-23.547555,-46.634687
64,Van Gogh Museum,Amsterdam,Netherlands,"1,364,023","Van Gogh Museum, Amsterdam, Netherlands","Van Gogh Museum, 7, Paulus Potterstraat, Oud-Z...",52.358367,4.88109
65,National Museum of Nature and Science,Tokyo,Japan,"1,350,000","National Museum of Nature and Science, Tokyo, ...","ÂõΩÁ´ãÁßëÂ≠¶ÂçöÁâ©È§®, Âè∞Êù±Âå∫, Êù±‰∫¨ÈÉΩ, 110-8718, Êó•Êú¨",35.7159,139.776688
66,Kunsthistorisches Museum,Vienna,Austria,"1,345,617","Kunsthistorisches Museum, Vienna, Austria","Kunsthistorisches Museum, 5, Burgring, K√§rntne...",48.203739,16.361782
67,Museo Nazionale di Castel Sant'Angelo,Rome,Italy,"1,321,834","Museo Nazionale di Castel Sant'Angelo, Rome, I...","Museo Nazionale di Castel Sant‚ÄôAngelo, 50, Lun...",41.90308,12.466181
69,Palacio de Cristal del Retiro,Madrid,Spain,"1,318,823","Palacio de Cristal del Retiro, Madrid, Spain","Estanque del Palacio de Cristal, Jer√≥nimos, Re...",40.413715,-3.681408
71,Scottish National Gallery,Edinburgh,United Kingdom,"1,277,230","Scottish National Gallery, Edinburgh, United K...","National Gallery, The Mound, Old Town, City of...",55.950881,-3.195619
72,National Gallery Singapore,Singapore,Singapore,NaN,"National Gallery Singapore, Singapore, Singapore","National Gallery Singapore, 1, Saint Andrew's ...",1.290256,103.851471
73,Museo Reina Sof√≠a,Madrid,Spain,"1,253,183","Museo Reina Sof√≠a, Madrid, Spain","Museo Nacional Centro de Arte Reina Sof√≠a, 52,...",40.40805,-3.694422

In [ ]:
import folium

In [ ]:
# initiate a folium map
m = folium.Map(location = [55.950881, -3.195619], zoom_start = 10)

In [ ]:
for index, row in museums.iterrows():

  # Info to display in popup
  popup_info = f"""
  Name: {row['Name']}<br><br>
  Full Address: {row['Full address']}<br><br>
  Latitude: {row['Latitude']}<br><br>
  Longitude: {row['Longitude']}
  """

  # Creating a marker
  folium.Marker(
      location = [row['Latitude'], row['Longitude']],
      popup = folium.Popup(popup_info, max_width = 300)
  ).add_to(m)

In [ ]:
m