<a href="https://colab.research.google.com/github/M339KUMAR/ColabDemoFiles/blob/main/GCAF/Gh_mbel_ClCh_xlsx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:


ClimateCh_df= pd.read_excel('/content/sample_data/climate_change.xls')
ClimateCh_df.columns

Index(['Country code', 'Country name',  'Series code',  'Series name',
              'SCALE',     'Decimals',           1990,           1991,
                 1992,           1993,           1994,           1995,
                 1996,           1997,           1998,           1999,
                 2000,           2001,           2002,           2003,
                 2004,           2005,           2006,           2007,
                 2008,           2009,           2010,           2011],
      dtype='object')

In [ ]:

ClimateCh_df.iloc[0:1, 0:28]

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,29.57481,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [ ]:


ClimateCh_df.loc[0:1]

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,29.57481,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [ ]:

ClimateCh_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13512 entries, 0 to 13511
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country code  13512 non-null  object
 1   Country name  13512 non-null  object
 2   Series code   13512 non-null  object
 3   Series name   13512 non-null  object
 4   SCALE         13512 non-null  object
 5   Decimals      13512 non-null  object
 6   1990          10017 non-null  object
 7   1991          10017 non-null  object
 8   1992          10017 non-null  object
 9   1993          10017 non-null  object
 10  1994          10017 non-null  object
 11  1995          10017 non-null  object
 12  1996          10017 non-null  object
 13  1997          10017 non-null  object
 14  1998          10017 non-null  object
 15  1999          10017 non-null  object
 16  2000          10017 non-null  object
 17  2001          10017 non-null  object
 18  2002          10017 non-null  object
 19  2003          10017 non-null  object
 20  2004          10017 non-null  object
 21  2005          10017 non-null  object
 22  2006          10017 non-null  object
 23  2007          10017 non-null  object
 24  2008          10017 non-null  object
 25  2009          10017 non-null  object
 26  2010          10017 non-null  object
 27  2011          12382 non-null  object
dtypes: object(28)
memory usage: 2.9+ MB

In [ ]:

ClimateCh_df['Country code'].describe()

count     13512
unique      233
top         ABW
freq         58
Name: Country code, dtype: object

In [ ]:

Unemp_df= pd.read_csv('/content/sample_data/unemployment.csv')
Unemp_df.head(2)

         date  unemployment state
0  1976-01-01           9.1    NM
1  1976-02-01           8.9    NM

In [ ]:

Unemp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7358 entries, 0 to 7357
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          7358 non-null   object
 1   unemployment  7358 non-null   float64
 2   state         7358 non-null   object
dtypes: float64(1), object(2)
memory usage: 172.6+ KB

In [ ]:


Unemp_df.columns

Index(['date', 'unemployment', 'state'], dtype='object')

In [ ]:

Unemp_df['state'].isna().sum()

0

In [ ]:


Unemp_df.describe()

       unemployment
count   7358.000000
mean       6.086178
std        2.073988
min        1.800000
25%        4.500000
50%        5.800000
75%        7.300000
max       17.700000

In [ ]:

ClimateCh_df.describe()

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
count,13512,13512,13512,13512,13512,13512,10017,10017,10017,10017,...,10017,10017,10017,10017,10017,10017,10017,10017,10017,12382
unique,233,233,58,58,2,3,4355,3398,3523,3583,...,3877,3869,4007,4484,4008,4047,4080,3506,2164,1434
top,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
freq,58,58,233,233,10017,5823,5163,6520,6364,6300,...,5960,5974,5792,4933,5781,5769,5414,6256,7685,10244

In [ ]:


ClimateCh_df['Country code'].unique()

array(['ABW', 'ADO', 'AFG', 'AGO', 'ALB', 'ARE', 'ARG', 'ARM', 'ASM',
       'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD',
       'BGR', 'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA',
       'BRB', 'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CHE', 'CHI', 'CHL',
       'CHN', 'CIV', 'CMR', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI',
       'CUB', 'CUW', 'CYM', 'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK',
       'DOM', 'DZA', 'EAP', 'ECA', 'ECU', 'EGY', 'EMU', 'ERI', 'ESP',
       'EST', 'ETH', 'FIN', 'FJI', 'FRA', 'FRO', 'FSM', 'GAB', 'GBR',
       'GEO', 'GHA', 'GIB', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD',
       'GRL', 'GTM', 'GUM', 'GUY', 'HIC', 'HKG', 'HND', 'HRV', 'HTI',
       'HUN', 'IDN', 'IMY', 'IND', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR',
       'ITA', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR',
       'KNA', 'KOR', 'KSV', 'KWT', 'LAC', 'LAO', 'LBN', 'LBR', 'LBY',
       'LCA', 'LIC', 'LIE', 'LKA', 'LMC', 'LMY', 'LSO', 'LTU', 'LUX',
       'LVA', 'MAC', 'MAF', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX',
       'MHL', 'MIC', 'MKD', 'MLI', 'MLT', 'MMR', 'MNA', 'MNE', 'MNG',
       'MNP', 'MOZ', 'MRT', 'MUS', 'MWI', 'MYS', 'MYT', 'NAM', 'NCL',
       'NER', 'NGA', 'NIC', 'NIU', 'NLD', 'NOR', 'NPL', 'NRU', 'NZL',
       'OMN', 'PAK', 'PAN', 'PER', 'PHL', 'PLW', 'PNG', 'POL', 'PRI',
       'PRK', 'PRT', 'PRY', 'PYF', 'QAT', 'ROM', 'RUS', 'RWA', 'SAS',
       'SAU', 'SDN', 'SEN', 'SGP', 'SID', 'SLB', 'SLE', 'SLV', 'SMR',
       'SOM', 'SRB', 'SSA', 'STP', 'SUR', 'SVK', 'SVN', 'SWE', 'SWZ',
       'SXM', 'SYC', 'SYR', 'TCA', 'TCD', 'TGO', 'THA', 'TJK', 'TKM',
       'TMP', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TZA', 'UGA', 'UKR',
       'UMC', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VIR', 'VNM', 'VUT',
       'WBG', 'WLD', 'WSM', 'YEM', 'ZAF', 'ZAR', 'ZMB', 'ZWE'],
      dtype=object)

In [ ]:

ClimateCh_df.columns

Index(['Country code', 'Country name',  'Series code',  'Series name',
              'SCALE',     'Decimals',           1990,           1991,
                 1992,           1993,           1994,           1995,
                 1996,           1997,           1998,           1999,
                 2000,           2001,           2002,           2003,
                 2004,           2005,           2006,           2007,
                 2008,           2009,           2010,           2011],
      dtype='object')

In [ ]:

ClimateCh_df[['Country code', 'Country name',  'Series code',  'Series name',
              'SCALE',     'Decimals',           1990,           1991,
                 1992,           1993,           1994,           1995,
                 1996,           1997,           1998,           1999,
                 2000,           2001,           2002,           2003,
                 2004,           2005,           2006,           2007,
                 2008,           2009,           2010,           2011
]].isna().sum()

Country code       0
Country name       0
Series code        0
Series name        0
SCALE              0
Decimals           0
1990            3495
1991            3495
1992            3495
1993            3495
1994            3495
1995            3495
1996            3495
1997            3495
1998            3495
1999            3495
2000            3495
2001            3495
2002            3495
2003            3495
2004            3495
2005            3495
2006            3495
2007            3495
2008            3495
2009            3495
2010            3495
2011            1130
dtype: int64

In [ ]:


#ClimateCh_df[2009].loc[13100:13150]

In [ ]:


X=ClimateCh_df['Decimals'].unique()
X[0:3]

array([1, 0, 'Text'], dtype=object)

In [ ]:


#sns.lineplot(data=ClimateCh_df, x= ClimateCh_df.index, y='Decimals')

ClimateCh_df[['Decimals',           1990,           1991,                 1992,           1993,           1994,           1995,
                 1996,           1997,           1998,           1999,
                 2000,           2001,           2002,           2003,
                 2004,           2005,           2006,           2007,
                 2008,           2009,           2010,           2011
]].isna().sum()

Decimals       0
1990        3495
1991        3495
1992        3495
1993        3495
1994        3495
1995        3495
1996        3495
1997        3495
1998        3495
1999        3495
2000        3495
2001        3495
2002        3495
2003        3495
2004        3495
2005        3495
2006        3495
2007        3495
2008        3495
2009        3495
2010        3495
2011        1130
dtype: int64

In [ ]:


ClimateCh_df[['Decimals',           1990,           1991,                 1992,           1993,           1994,           1995,
                 1996,           1997,           1998,           1999,
                 2000,           2001,           2002,           2003,
                 2004,           2005,           2006,           2007,
                 2008,           2009,           2010,           2011
]].dropna()

,Decimals,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,1,29.57481,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,1,0,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,1,0,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,1,0.208235,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,1,4.967875,..,..,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13507,0,2497175.681,2693642.2632,2909756.3552,3139637.3184,3373929.855,3605264.936,3817581.273,4024280.624,4229363.05,...,5148619.3146,5410331.206,5683412.0046,5967457.827,6275723.036,6597265.194,6932788.708,7283068.4108,7648699.452,..
13508,0,18304000,18864881.576074,19446091.545173,20048481.072485,20672940.243054,21320400,21992135.775175,22697594.561064,23438682.545585,...,26345562.7512,26904362.5996,27448218.3022,27988692.117,28533559.5188,29079838.1332,29636881.5628,30193795.83,30844632.1,..
13509,0,10120930.828,10569454.3904,11060046.8476,11568627.5584,12061489.8516,12515132.796,12990617.1852,13428559.416,13852037.716,...,16125336.2688,16867832.791,17640845.614,18431987.562,19333729.388,20261443.145,21216476.3796,22201848.3232,23219959.84,..
13510,0,3096860.882,3141668.2968,3183257.2304,3223514.6742,3264940.1844,3309118.176,3356931.5184,3407475.816,3458431.1176,...,3729882.6848,3819640.7412,3912870.7312,4011827.75,4128986.897,4253139.4752,4384858.5704,4524564.0776,4614728.013,..
13511,0,3036068.58,3175022.711,3310511.552,3443081.8224,3574012.1152,3704047.681,3819482.348,3932953.2826,4041470.1632,...,4367338.8024,4422102.3736,4469726.7596,4512876.274,4558288.489,4600586.907,4649406.1562,4717663.7744,4814866.882,..

In [ ]:
'''
if(
ClimateCh_df['SCALE'].unique()=='Text').any():
 print(ClimateCh_df.index)'''

X=len(ClimateCh_df['SCALE'])
X

'''for idx in len(ClimateCh_df['SCALE']):
  if ClimateCh_df['SCALE'].any()=='Text':
      print('index at ',idx)'''

"for idx in len(ClimateCh_df['SCALE']):\n  if ClimateCh_df['SCALE'].any()=='Text':\n      print('index at ',idx)"